Class {
	#name : #UFFIOpenGLSpecCommandParam,
	#superclass : #Object,
	#instVars : [
		'name',
		'type'
	],
	#category : #'UFFIOpenGL-Generator'
}

{ #category : #accessing }
UFFIOpenGLSpecCommandParam >> name [
	^ name
]

{ #category : #accessing }
UFFIOpenGLSpecCommandParam >> name: anObject [
	name := anObject
]

{ #category : #accessing }
UFFIOpenGLSpecCommandParam >> type [
	^ type
]

{ #category : #accessing }
UFFIOpenGLSpecCommandParam >> type: anObject [
	type := anObject
]
